### ISSUE TITLE
Optional List support

### ISSUE THREAD

**Issue by Mokto** [eigenein/protobuf#106]
Would be nice to support `Optional[List]` 👍

**Comment by eigenein** [comment]
Hi @Mokto,

Sorry for the slow response, haven't realized that `foo: Optional[List[...]] = field(…, default=None)` (in v2) and `foo: Annotated[Optional[list[...]]] = None` (in v3) should already work as expected.

Did you encounter some bug with it?

**Comment by eigenein** [comment]
Oh, disregard the comment, I can see the problem in v2: it doesn't check for `None` in repeated fields when serializing. I think I can add it.

The v3 already does the check

**Comment by Mokto** [comment]
Cool! Just waiting for v3 to be released so I can test it then.

**Comment by eigenein** [comment]
@Mokto :+1: If you're willing to give it a try, there's `3.0.0a3` published on PyPI already
