### ISSUE TITLE
Empty list of proto seems to be broken

### ISSUE THREAD

**Issue by oroulet** [eigenein/protobuf#111]
If I define a proto containing a list of builtins, everything is fine, if I create a proto containing a list of protos then loading seems to fails (although it can the generated bytes that are wrong too)

```
from dataclasses import dataclass
from typing import List
from pure_protobuf.dataclasses_ import field, message


@message
@dataclass
class MyData:
    a: float = field(1)


@message
@dataclass
class ManyThings:
    mylist: List[float] = field(1)
    myemptylist: List[float] = field(2)


@message
@dataclass
class ManyThings2:
    mydatalist: List[MyData] = field(1)
    myemptydatalist: List[MyData] = field(2)


if __name__ == "__main__":
    d = MyData(1.0)
    m = ManyThings([1.0], [])
    mybytes = m.dumps()
    res = ManyThings.loads(mybytes)
    print(res)
    m2 = ManyThings2([d, d], [])
    mybytes2 = m2.dumps()
    res = ManyThings2.loads(mybytes2)
    print(res)
```

result:
```
ManyThings(mylist=[1.0], myemptylist=[])
Traceback (most recent call last):
  File "/home/olivier/kurant/dev/ipc/tt/t2.py", line 34, in <module>
    res = ManyThings2.loads(mybytes2)
  File "/home/olivier/.virtualenvs/grab/lib/python3.10/site-packages/pure_protobuf/dataclasses_.py", line 111, in loads
    return load(cls, io)
  File "/home/olivier/.virtualenvs/grab/lib/python3.10/site-packages/pure_protobuf/dataclasses_.py", line 103, in load
    return cls.serializer.load(io)
  File "/home/olivier/.virtualenvs/grab/lib/python3.10/site-packages/pure_protobuf/serializers/__init__.py", line 438, in load
    return self.type_(**values)
TypeError: ManyThings2.__init__() missing 1 required positional argument: 'myemptydatalist'

```

**Comment by oroulet** [comment]
I did a few tests comparing to data generate by protobuf from google and it looks like the issue is in the loader. The generated data seems OK

**Comment by eigenein** [comment]
Hi @oroulet,

I believe it works as designed:

## `class ManyThings`

Here you got a list of `float`, so a list of primitive scalar values, which uses the packed representation by default, that in turn results in a record in the output representing an empty byte string. This is important, because when you load it back, the parser gets a value for `myemptylist`. Hence, no error.

## `class ManyThings2`

Here you have a list of embedded messages, and by definition, it cannot use the packed representation. This means, for the empty list, there's no corresponding record in the output, at all. When you load it, the value for `myemptydatalist` is missing, hence the error.

You should specify `field(2, default_factory=list)` to fix this, otherwise, the parser assumes a required list.

**Comment by oroulet** [comment]
I am not sure I understand the reasoning, but at least you provide a working workaround, and it looks like it solves my case nicely. Thanks!

**Comment by oroulet** [comment]
but fyi I tested the same with the new proto3 syntax and there it is the first case that seems to fail (If I am not making any mistake:

```
from dataclasses import dataclass, field
from typing import List
from io import BytesIO

from pure_protobuf.annotations import Field
from pure_protobuf.message import BaseMessage
from typing_extensions import Annotated


@dataclass
class MyData(BaseMessage):
    a: Annotated[float, Field(1)]


@dataclass
class ManyThings(BaseMessage):
    mylist: Annotated[List[float], Field(1)]
    myemptylist: Annotated[List[float], Field(2)] = field(default_factory=list)


@dataclass
class ManyThings2(BaseMessage):
    mylist: Annotated[List[MyData], Field(1)]
    myemptylist: Annotated[List[MyData], Field(2)] = field(default_factory=list)


if __name__ == "__main__":
    d = MyData(1.0)
    m = ManyThings([1.0], [])
    mybytes = bytes(m)
    print(mybytes)
    res = ManyThings.read_from(BytesIO(mybytes))
    #print(res)
    m2 = ManyThings2([d, d], [])
    mybytes2 = bytes(m2)
    print(mybytes2)
    res = ManyThings2.read_from(BytesIO(mybytes2))
    print(res)
    ```
    
    output:
    ```
    b'\n\x04\x00\x00\x80?\x12\x00'
Traceback (most recent call last):
  File "/home/olivier/dev/protobuf/tt/t3.py", line 32, in <module>
    res = ManyThings.read_from(BytesIO(mybytes))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olivier/dev/protobuf/pure_protobuf/message.py", line 83, in read_from
    values[name] = descriptor.accumulate(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olivier/dev/protobuf/pure_protobuf/_accumulators.py", line 33, in __call__
    accumulator.extend(other)
  File "/home/olivier/dev/protobuf/pure_protobuf/io/wrappers.py", line 47, in __call__
    yield from self.inner_packed(io)
  File "/home/olivier/dev/protobuf/pure_protobuf/io/wrappers.py", line 64, in __call__
    yield from self.inner(BytesIO(read_bytes(io)))
  File "/home/olivier/dev/protobuf/pure_protobuf/io/wrappers.py", line 79, in __call__
    yield from self.inner(io)
  File "/home/olivier/dev/protobuf/pure_protobuf/io/struct_.py", line 21, in __call__
    yield from inner.unpack(io.read(inner.size))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: unpack requires a buffer of 4 bytes

```

**Comment by oroulet** [comment]
Also maye I ask what the reasoning is for change version 3 changes? replacing the dumps and loads by requiring IOBytes seems a but heavy and unnecessary. many serializatoin libraries use these methods.

Also I was using both @message and @json_dataclass. They work nicely together, now I am a bit unsure how to do that with version 3

**Comment by eigenein** [comment]
> Also may I ask what the reasoning is for the version 3 changes?

- V2 relies on `dataclasses`, whereas V3 only needs a class' `__init__()` to accept named arguments, hence compatible with i.e. Pydantic, and doesn't require either of these per se
- Better typing: both the API and compatibility with `Annotated`
- I've reworked the internals for better extensibility, although I still need to write the docs on that

> replacing the `dumps` and `loads` by requiring IOBytes seems a bit heavy and unnecessary. many serializatoin libraries use these methods.

`dumps` still kind of exists, just call `bytes(message)`. Accepting a stream, though, now allows reading/writing messages from/to a generic stream without a need to keep whole serialized messages in memory. What's this question about? If you need `loads()`, it's a 2-liner – I can easily add it, no big deal

> Also I was using both `@message` and `@json_dataclass`. They work nicely together, now I am a bit unsure how to do that with version 3

I'm not sure what the problem is, can you elaborate?

**Comment by eigenein** [comment]
Sorry for the delay, I'll look at the [`struct.error`](https://github.com/eigenein/protobuf/issues/111#issuecomment-1520585560) later today, that shouldn't happen

**Comment by oroulet** [comment]
> Sorry for the delay, I'll look at the https://github.com/eigenein/protobuf/issues/111#issuecomment-1520585560 later today, that shouldn't happen

No problem. You solved my issue by telling me to add a default value. I only reported the following bug to help improve your software

>> dumps still kind of exists, just call bytes(message). Accepting a stream, though, now allows reading/writing messages from/to a generic stream without a need to keep whole serialized messages in memory. What's this question about? If you need loads(), it's a 2-liner – I can easily add it, no big deal

It is not a big deal. It just looks like a non-necessary change that breaks compatibility for no clear advantage. No problem for me. I was just mentioning.

**Comment by eigenein** [comment]
> It is not a big deal. It just looks like a non-necessary change that breaks compatibility for no clear advantage. No problem for me. I was just mentioning.

Fair enough, now that brought it up, it makes sense

`3.0.0a3` fixes the `struct.error: unpack requires a buffer of 4 bytes` (that was a bug), and brings back `Message.loads()` and `Message.dumps()`
