### ISSUE TITLE
Convert to dict

### ISSUE THREAD

**Issue by hongquan** [eigenein/protobuf#62]
I'm using `pure_protobuf` in a Django project where I want to support both REST API and WebSocket+Protobuf.

I want to reuse DjangoRestFramework serializers to validate the data before saving to database. It expects input to be `dict`. So it will be nice if `pure_protobuf` support to convert the PB3 message to `dict`.

**Comment by eigenein** [comment]
Hi @hongquan,

Are you using the legacy interface or `pure_protobuf.dataclasses_`? I recommend using the latter one and it supports the standard [`dataclasses`](https://docs.python.org/3/library/dataclasses.html) which have [`asdict`](https://docs.python.org/3/library/dataclasses.html#dataclasses.asdict) method

**Comment by hongquan** [comment]
@eigenein Thank you for quick reply. I am using the `pure_protobuf.dataclasses_` interface and didn't know that `asdict` method.
It solves my question.
